#!/bin/bash

set -ex

NAME=${1:-cmtrace}

echo "INFO: Creating release archive ${NAME}.tar.gz"

./build-all-targets debug
./build-all-targets minSizeRel
cp -R libcmtrace-test dist
tar czf ${NAME}.tar.gz dist