#!/bin/bash

set -ex

PRESET=${1:-minSizeRel}

ARM_NONE_EABI=`which arm-none-eabi-gcc || true`
if [[ ! -z "$ARM_NONE_EABI" ]]; then
    # if ARM_NONE_EABI toolchain seems to be present
    #./buildit on/cortex-m0 $PRESET
    ./buildit on/cortex-m3 $PRESET
    ./buildit on/cortex-m4 $PRESET
    ./buildit on/cortex-m7 $PRESET
    #./buildit on/cortex-m23 $PRESET
    ./buildit on/cortex-m33 $PRESET
    #./buildit on/cortex-m35p $PRESET
    #./buildit on/cortex-m52 $PRESET
    #./buildit on/cortex-m55 $PRESET
    #./buildit on/cortex-m85 $PRESET
fi

OUT=dist/$PRESET/libcmtrace
rm -rf $OUT
mkdir -p $OUT
#cp LICENSE $OUT
cp -R libcmtrace/include $OUT
cp -R libcmtrace/source $OUT
mv build $OUT
git status
git diff package.json
sha256sum package.json
git describe --tags --always --dirty --match "v*" > $OUT/version.txt
cd dist/$PRESET
OUT_FILE=libcmtrace-$PRESET.tar.gz
tar czf $OUT_FILE libcmtrace
sha256sum $OUT_FILE > $OUT_FILE.sha256sum
cd ../..
rm -rf $OUT
mv dist/$PRESET/* dist
rm -rf dist/$PRESET